/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "outline-variant": "#bbcbb8",
        "on-tertiary-container": "#003e89",
        "on-secondary-container": "#572000",
        "on-primary-container": "#004c1b",
        "primary-container": "#00c853",
        "on-secondary-fixed-variant": "#7a3000",
        "background": "#fcf9f8",
        "status-processing": "#FF6B00",
        "surface-variant": "#e5e2e1",
        "secondary-fixed-dim": "#ffb693",
        "primary-fixed": "#69ff87",
        "inverse-on-surface": "#f3f0ef",
        "on-primary-fixed": "#002108",
        "surface-tint": "#006e2a",
        "surface-container-highest": "#e5e2e1",
        "primary": "#006e2a",
        "on-error-container": "#93000a",
        "on-surface-variant": "#3c4a3c",
        "inverse-primary": "#3ce36a",
        "tertiary": "#005ac1",
        "surface-background": "#FFFFFF",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-background": "#1b1c1c",
        "outline": "#6c7b6a",
        "surface-container": "#f0eded",
        "tertiary-fixed-dim": "#adc6ff",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#351000",
        "ui-divider": "#E0E0E0",
        "surface-dim": "#dcd9d9",
        "inverse-surface": "#303030",
        "secondary-container": "#fe6b00",
        "tertiary-fixed": "#d8e2ff",
        "surface-container-high": "#eae7e7",
        "surface": "#fcf9f8",
        "primary-fixed-dim": "#3ce36a",
        "tertiary-container": "#84adff",
        "secondary": "#a04100",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-fixed": "#001a41",
        "secondary-fixed": "#ffdbcc",
        "on-surface": "#1b1c1c",
        "on-primary-fixed-variant": "#00531e",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "surface-bright": "#fcf9f8",
        "status-success": "#00C853",
        "status-error": "#FF0000",
        "on-tertiary-fixed-variant": "#004494"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "xs": "4px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "gutter": "16px",
        "sm": "8px",
        "container-max": "1536px",
        "base": "4px"
      },
      "fontFamily": {
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "display-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg": ["Be Vietnam Pro", "sans-serif"],
        "headline-md": ["Be Vietnam Pro", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"]
      },
      "fontSize": {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-caps": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "code-sm": ["12px", {"lineHeight": "16px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
